---
- name: Get Vector archive
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "./vector-{{ vector_version }}.tar.gz"
    mode: '0644'

- name: Create vector directory
  ansible.builtin.file:
    path: "~/{{ vector_dir }}"
    state: directory
    mode: '0755'

- name: Unarchive Vector archive
  ansible.builtin.unarchive:
    src: ~/vector-{{ vector_version }}.tar.gz
    dest: "~/{{ vector_dir }}"
    remote_src: true
    extra_opts:
      - --strip-components=2

- name: Create Vector systemd unit
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Start Vector service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    daemon_reload: true
