---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos_8
    image: hendrik44/molecule-docker-systemd-centos:8
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - create
    - converge
    - destroy