---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos_8
    image: hendrik44/molecule-docker-systemd-centos:8
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
provisioner:
  name: ansible
verifier:
  name: ansible
